import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Container from "../../components/Container";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import { Text } from "../../components/Text";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Real English</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Container>About</Container>
      <Footer></Footer>
    </div>
  );
};

export default About;
