import type { NextPage } from "next";
import Head from "next/head";
import Image, { StaticImageData } from "next/image";
import styled from "styled-components";
import Flex from "../components/Box/Flex";
import Container from "../components/Container";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { Text } from "../components/Text";
import BannerImg from "../assets/images/home/banner_1.png";
import Stats1 from "../assets/images/home/stats_1.png";
import Stats2 from "../assets/images/home/stats_2.png";
import Stats3 from "../assets/images/home/stats_3.png";
import Circle1 from "../assets/images/home/circle_1.png";
import Circle2 from "../assets/images/home/circle_2.png";
import Circle3 from "../assets/images/home/circle_3.png";
import IconCall from "../assets/icons/call-calling.png";
import IconGetFile from "../assets/icons/get-file.png";
import IconArrowRight from "../assets/icons/arrow-right.png";
import { getEvents, getPosts } from "../utils/wordpress";
import Post from "../components/Post";
import colors from "../constants/colors";
import Button from "../components/Button";

import Slider from "react-slick";
interface IBanner {
  img?: string | StaticImageData;
}
interface ICourseItem {
  active?: boolean;
}
const StyledBanner = styled.div<IBanner>`
  //@ts-ignore
  background: url(${BannerImg.src}) no-repeat right center,
    url(${Circle3.src}) no-repeat left bottom,
    url(${Circle2.src}) no-repeat 60% 20%, url(${Circle1.src}) no-repeat 95% 90%;

  width: 100%;
  height: 100vh;
`;
const BannerContent = styled(Container)`
  display: flex;
  flex-direction: column;
  justify-content: center;
  height: 100%;

  & > div {
    width: 50%;
  }
  & > button {
    margin: 54px 0;
  }
`;
const Heading = styled.div`
  font-weight: 700;
  font-size: 64px;
  line-height: 80px;
  color: ${colors.text};
  margin-bottom: 54px;
  position: relative;
  &:after {
    content: "";
    display: block;
    width: 65%;
    height: 90px;
    border: 3px solid #f4a242;
    border-radius: 50%;
    position: absolute;
    top: -10px;
    right: 15%;
    z-index: -1;
  }
`;
const Stats = styled(Flex)`
  width: 70% !important;
`;
const CourseList = styled.div`
  margin-bottom: 64px;
`;
const CourseItem = styled(Flex)<ICourseItem>`
  width: 240px;
  padding: 16px;
  border-radius: 16px;
  background: #fff;
  border: ${(props) => (props.active ? "1px solid #f4a242" : "1px solid #fff")};
  // flex-shrink: 0;
`;
const Home: NextPage = ({ posts }: any) => {
  // console.log(posts);
  // const jsxPosts = posts.map((post: any) => {
  //   const featuredMedia = post["_embedded"]["wp:featuredmedia"][0];
  //   return <Post post={post} featuredMedia={featuredMedia} key={post.id} />;
  // });
  return (
    <div>
      <Head>
        <title>Real English</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>

      <StyledBanner>
        <BannerContent>
          <Heading>
            The Real IELTS <br />
            IELTS Đích thực
          </Heading>
          <Text color={colors.regular}>
            The Real IELTS ra đời với mục đích xóa tan nỗi sợ tiếng Anh của
            người Việt. Chương trình học IELTS đầu tiên áp dụng từ độ tuổi 12
            vận dụng các phương pháp học kết hợp tâm lý học và công nghệ vào
            việc tiếp thu kiến thức.
          </Text>
          <Text color={colors.sub} fontSize="20px" bold>
            Học thật - Thi thật - Chứng chỉ thật
          </Text>
          <Button variant="primary">
            <Text color={colors.tertiary} bold>
              Đăng ký
            </Text>
          </Button>
          <Stats justifyContent="space-between">
            <Flex flexDirection="column">
              <Text fontSize="20px" bold color={colors.sub}>
                20+
              </Text>
              <Flex>
                <Image src={Stats1} alt="Giáo viên tài năng" />
                <Text color={colors.disable}>Giáo viên tài năng</Text>
              </Flex>
            </Flex>
            <Flex flexDirection="column">
              <Text fontSize="20px" bold color={colors.sub}>
                2000+
              </Text>
              <Flex>
                <Image src={Stats2} alt="Học viên đang theo học" />
                <Text color={colors.disable}>Học viên đang theo học</Text>
              </Flex>
            </Flex>
            <Flex flexDirection="column">
              <Text fontSize="20px" bold color={colors.sub}>
                1000+
              </Text>
              <Flex>
                <Image src={Stats3} alt="Học viên cán đích" />
                <Text color={colors.disable}>Học viên cán đích</Text>
              </Flex>
            </Flex>
          </Stats>
        </BannerContent>
      </StyledBanner>
      <div
        style={{
          background: "#F7F7F8",
          padding: "64px 0",
        }}
      >
        <Container flexDirection="column">
          <Text
            color={colors.text}
            fontSize="48px"
            style={{
              marginBottom: "48px",
            }}
          >
            Khoá học
          </Text>
          <CourseList>
            <Slider slidesToScroll={3} slidesToShow={3} infinite={false}>
              <div>
                <CourseItem
                  active
                  flexDirection="column"
                  alignItems="center"
                  gap="16px"
                >
                  <Text bold color={colors.active}>
                    IELTS Starlight
                  </Text>
                  <Text color={colors.text}>IELTS 0 - 7.5+ cho học sinh</Text>
                </CourseItem>
              </div>
              <div>
                <CourseItem
                  flexDirection="column"
                  alignItems="center"
                  gap="16px"
                >
                  <Text bold color={colors.text}>
                    Advance Package
                  </Text>
                  <Text color={colors.text}>Combo 0-7.5+</Text>
                </CourseItem>
              </div>
              <div>
                <CourseItem
                  flexDirection="column"
                  alignItems="center"
                  gap="16px"
                >
                  <Text bold color={colors.text}>
                    Modest Package
                  </Text>
                  <Text color={colors.text}>Combo 0-5.0+</Text>
                </CourseItem>
              </div>
              <div>
                <CourseItem
                  flexDirection="column"
                  alignItems="center"
                  gap="16px"
                >
                  <Text bold color={colors.text}>
                    Fluent Package
                  </Text>
                  <Text color={colors.text}>Combo 0-6.5+</Text>
                </CourseItem>
              </div>
              <div>
                <CourseItem
                  flexDirection="column"
                  alignItems="center"
                  gap="16px"
                >
                  <Text bold color={colors.text}>
                    Private Package
                  </Text>
                  <Text color={colors.text}>Gia sư 1-1</Text>
                </CourseItem>
              </div>
            </Slider>
          </CourseList>
          <Button
            variant="secondary"
            startIcon={<Image src={IconCall} alt="Call" />}
            style={{
              margin: "0 auto",
              marginBottom: "120px",
            }}
          >
            <Text color={colors.tertiary} bold>
              Đăng ký nhận tư vấn ngay
            </Text>
          </Button>
        </Container>
        <Container
          gap="92px"
          alignItems="center"
          style={{
            marginBottom: "64px",
          }}
        >
          <div
            style={{
              width: "750px",
              height: "420px",
              background: "#D9D9D9",
            }}
          ></div>
          <Flex flexDirection="column" gap="48px">
            <Text bold fontSize="48px" color={colors.h1}>
              Phương pháp đào tạo{" "}
              <span style={{ color: colors.active }}>LCLT</span>
            </Text>
            <Flex flexDirection="column" gap="16px">
              <Text bold fontSize="20px" color={colors.sub}>
                Learner Centered
              </Text>
              <Text color={colors.regular}>Lấy người học làm trọng tâm</Text>
            </Flex>
            <Flex flexDirection="column" gap="16px">
              <Text bold fontSize="20px" color={colors.sub}>
                Linguistic Thinking
              </Text>
              <Text color={colors.regular}>Xây dựng tư duy Ngôn ngữ</Text>
            </Flex>
          </Flex>
        </Container>
        <Container
          justifyContent="center"
          gap="24px"
          style={{ marginBottom: "120px" }}
        >
          <Button
            variant="secondary"
            endIcon={<Image src={IconGetFile} alt="Call" />}
          >
            <Text color={colors.tertiary} bold>
              File phương pháp học
            </Text>
          </Button>
          <Button
            variant="tertiary"
            endIcon={<Image src={IconArrowRight} alt="Call" />}
          >
            <Text color={colors.secondary} bold>
              Tìm hiểu thêm
            </Text>
          </Button>
        </Container>
      </div>
      <Footer></Footer>
    </div>
  );
};

export default Home;
export async function getStaticProps({ params }: any) {
  const posts = await getPosts();
  const events = await getEvents();
  return {
    props: {
      posts,
      events,
    },
    revalidate: 10, // In seconds
  };
}
