import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styled from "styled-components";
import Banner from "../../assets/images/about/banner.png";
import Flex from "../../components/Box/Flex";
import Grid from "../../components/Box/Grid";
import Button from "../../components/Button";
import Container from "../../components/Container";
import Footer from "../../components/Footer";
import Header from "../../components/Header";
import { Text } from "../../components/Text";
import colors from "../../constants/colors";
const StyledBanner = styled.div`
  height: 80vh;
  background: url(${Banner.src}) no-repeat center center;
  background-size: 100vw;
  margin-bottom: 50px;
`;
const StyledInput = styled.input`
  width: 70%;
  padding: 12px 0;
  border: none;
  color: #ced3e0;
  border-bottom: 1px solid #ced3e0;
  font-size: 14px;
  color: ${colors.disable};
`;
const Courses: NextPage = () => {
  return (
    <>
      <Head>
        <title>Real English</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledBanner></StyledBanner>
      <Container flexDirection="column">
        <Text
          color={colors.h1}
          fontSize="48px"
          bold
          style={{
            marginBottom: "48px",
          }}
        >
          Khoá học
        </Text>
        <Grid
          columns="3"
          gap="64px"
          style={{
            width: "100%",
            marginBottom: "110px",
          }}
        >
          <Flex flexDirection="column" gap="16px">
            <Link href="courses/ielts-starlight">
              <Text fontSize="20px" color={colors.active} bold pointer>
                IELTS Starlight
              </Text>
            </Link>

            <Text color={colors.regular}>IELTS 0 - 7.5+ cho học sinh</Text>
          </Flex>
          <Flex flexDirection="column" gap="16px">
            <Link href="courses/modest-package">
              <Text fontSize="20px" color={colors.active} bold pointer>
                Modest Package
              </Text>
            </Link>
            <Text color={colors.regular}>Combo 0-5.0+</Text>
          </Flex>
          <Flex flexDirection="column" gap="16px">
            <Link href="courses/fluent-package">
              <Text fontSize="20px" color={colors.active} bold pointer>
                Fluent Package
              </Text>
            </Link>
            <Text color={colors.regular}>Combo 0-6.5+</Text>
          </Flex>
          <Flex flexDirection="column" gap="16px">
            <Link href="courses/advance-package">
              <Text fontSize="20px" color={colors.active} bold pointer>
                Advance Package
              </Text>
            </Link>
            <Text color={colors.regular}>Combo 0-7.5+</Text>
          </Flex>
          <Flex flexDirection="column" gap="16px">
            <Link href="courses/private-package">
              <Text fontSize="20px" color={colors.active} bold pointer>
                Private Package
              </Text>
            </Link>
            <Text color={colors.regular}>Gia sư 1-1</Text>
          </Flex>
        </Grid>
      </Container>
      <Text
        color={colors.h1}
        fontSize="48px"
        bold
        center
        style={{
          marginBottom: "48px",
        }}
      >
        ĐĂNG KÝ HỌC THỬ MIỄN PHÍ
      </Text>
      <Container
        flexDirection="column"
        gap="48px"
        alignItems="center"
        style={{
          marginBottom: "180px",
        }}
      >
        <StyledInput
          type="text"
          id="Name"
          name="Name"
          placeholder="Họ và tên"
        />
        <StyledInput
          type="tel"
          id="Tel"
          name="Tel"
          placeholder="Số điện thoại"
        />
        <StyledInput type="email" id="Email" name="Email" placeholder="Email" />
        <Button
          variant="secondary"
          style={{
            margin: "0 auto",
          }}
        >
          <Text color={colors.tertiary} bold>
            Đăng ký
          </Text>
        </Button>
      </Container>
    </>
  );
};

export default Courses;
